global:
  scrape_interval: 2s

scrape_configs:
  - job_name: 'gateway-service'
    scrape_interval: 2s
    metrics_path: '/actuator/prometheus'
    static_configs:
      - targets: [ 'gateway:8080' ]
