version: "3.8"

services:

  redis:
    container_name: "hayat_redis_test"
    image: redis:latest
    network_mode: "host"
    ports:
      - "6379:6379"

  mongo:
    image: mongo:latest
    container_name: "hayat_mongodb_dev"
    env_file:
      - .env
    ports:
      - "27017:27017"

volumes:
  hayat_mongodb: