apiVersion: v1
kind: Service
metadata:
  name: gateway-service
spec:
  ports:
    - protocol: TCP
      port: 8080
      targetPort: 8080
  selector:
    app: gateway-service
  type: LoadBalancer

---

apiVersion: v1
kind: Service
metadata:
  name: discovery-service
spec:
  selector:
    app: discovery-service
  ports:
    - name: http
      port: 8761
      targetPort: 8761
  type: ClusterIP

---

apiVersion: v1
kind: Service
metadata:
  name: config-service
spec:
  selector:
    app: config-service
  ports:
    - name: http
      port: 8111
      targetPort: 8111
  type: ClusterIP

---

apiVersion: v1
kind: Service
metadata:
  name: authorization-service
spec:
  selector:
    app: authorization-service
  ports:
    - name: http
      port: 8083
      targetPort: 8083
  type: ClusterIP

---

apiVersion: v1
kind: Service
metadata:
  name: donations-service
spec:
  selector:
    app: donations-service
  ports:
    - name: http
      port: 8084
      targetPort: 8084
  type: ClusterIP

---

apiVersion: v1
kind: Service
metadata:
  name: needs-service
spec:
  selector:
    app: needs-service
  ports:
    - name: http
      port: 8082
      targetPort: 8082
  type: ClusterIP

