donation:
  food:
    expiration_in_days: 45
jwt:
  token:
    expire: 36000000
    refresh:
      expire: 864000000
    secret:
      key: 01234##56789@@hayat$$donations
keycloak:
  auth-server-url: http://localhost:8181
  bearer-only: true
  credentials:
    username: authorization-service
    password: authorization-service
    client-id: authorization-service
    secret: authorization-service
  public-client: true
  realm: master
  resource: authorization-service
  ssl-required: external
otp:
  token:
    expire: 10
secret-key: 01234##56789@@hayat$$donations
server:
  port: 8082

eureka:
  instance:
    hostname: localhost
    nonSecurePort: 8761

spring:
  application:
    name: authorization-service
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    driverClassName: com.mysql.cj.jdbc.Driver
    password: harera
    url: jdbc:mysql://localhost:3306/hayat?useSSL=false&useUnicode=true&characterEncoding=UTF-8&allowPublicKeyRetrieval=true
    username: root
  hibernate:
    connection:
      charSet: UTF-8
      characterEncoding: utf8
      useUnicode: true
  jpa:
    generate-ddl: false
    hibernate:
      ddl-auto: none
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL5Dialect
        format_sql: false
  liquibase:
    change-log: classpath:db/main/changelog/changelog-main.yaml
    clear-checksums: true
  main:
    allow-bean-definition-overriding: true
  redis:
    host: redis
    lettuce:
      pool:
        max-active: 8
        max-idle: 8
        max-wait: -1
        min-idle: 0
    port: 6379
    timeout: 2000
