donation:
  food:
    expiration_in_days: 45
jwt:
  token:
    expire: 36000000
    refresh:
      expire: 864000000
    secret:
      key: ${SECRET_KEY}
keycloak:
  auth-server-url: ${KEYCLOAK_SERVICE_URL}
  realm: ${KEYCLOAK_REALM}
  credentials:
    username: ${KEYCLOAK_ADMIN}
    password: ${KEYCLOAK_ADMIN_PASSWORD}
    client-id: ${KEYCLOAK_AUTHORIZATION_CLIENT_ID}
    secret: ${KEYCLOAK_AUTHORIZATION_CLIENT_SECRET}
server:
  port: 8083
eureka:
  client:
    service-url:
      defaultZone: ${EUREKA_URL:http://localhost:8761}/eureka/

spring:
  application:
    name: authorization-service
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    driverClassName: com.mysql.cj.jdbc.Driver
    password: harera
    url: jdbc:mysql://${DB_HOST}:${DB_PORT}/hayat?useSSL=false&useUnicode=true&characterEncoding=UTF-8&allowPublicKeyRetrieval=true
    username: root
  hibernate:
    connection:
      charSet: UTF-8
      characterEncoding: utf8
      useUnicode: true
  jpa:
    generate-ddl: false
    hibernate:
      ddl-auto: none
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL5Dialect
        format_sql: false
  liquibase:
    change-log: classpath:db/main/changelog/changelog-main.yaml
    clear-checksums: true
    enabled: false
  main:
    allow-bean-definition-overriding: true
  data:
    redis:
      host: ${REDIS_HOST}
      lettuce:
        pool:
          max-active: 8
          max-idle: 8
          max-wait: -1
          min-idle: 0
      port: 6379
      timeout: 2000

sms:
  config:
    environment: ${SMS_ENV}
    username: ${SMS_USERNAME}
    password: ${SMS_PASSWORD}
    sender: ${SMS_SENDER}
    language: ${SMS_LANGUAGE}
  schemaless:
    config:
      url: https://smsmisr.com/api/SMS/
  schema:
    config:
      url: https://smsmisr.com/api/vSMS/
