server:
  port: 8085
spring:
  application:
    name: shared-service
  security:
    jackson:
      serialization:
        write-dates-as-timestamps: false
      deserialization:
        accept-single-value-as-array: true
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: http://0.0.0.0:8181/realms/master
          jwk-set-uri: http://0.0.0.0:8181/realms/master/protocol/openid-connect/certs
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    driverClassName: com.mysql.cj.jdbc.Driver
    password: harera
    url: jdbc:mysql://${DB_HOST}:${DB_PORT}/hayat?useSSL=false&useUnicode=true&characterEncoding=UTF-8&allowPublicKeyRetrieval=true
    username: root
  hibernate:
    connection:
      charSet: UTF-8
      characterEncoding: utf8
      useUnicode: true
  jpa:
    generate-ddl: false
    hibernate:
      ddl-auto: none
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL5Dialect
        format_sql: false
  liquibase:
    change-log: classpath:db/main/changelog/changelog-main.yaml

eureka:
  instance:
    hostname: localhost
    nonSecurePort: 8761
