server:
  port: 8085
spring:
  application:
    name: shared-service
  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: ${ISSUER_URI}/realms/master
          jwk-set-uri: ${ISSUER_URI}/realms/master/protocol/openid-connect/certs
  datasource:
    driverClassName: com.mysql.cj.jdbc.Driver
    password: ${DB_PASSWORD}
    url: jdbc:mysql://${DB_HOST}:${DB_PORT}/hayat?useSSL=false&useUnicode=true&characterEncoding=UTF-8&allowPublicKeyRetrieval=true
    username: root
  hibernate:
    connection:
      charSet: UTF-8
      characterEncoding: utf8
      useUnicode: true
  liquibase:
    change-log: classpath:db/main/changelog/changelog-main.yaml

eureka:
  client:
    service-url:
      defaultZone: ${EUREKA_URL:http://localhost:8761}/eureka/