server:
  port: 8443

spring:
  application:
    name: gateway

  cloud:
    gateway:
      discovery:
        locator:
          enabled: true
          lowerCaseServiceId: true
      routes:
        - id: needs-service
          uri: lb://needs-service
          predicates:
            - Path=/api/v1/needs/**
        - id: authorization-service
          uri: lb://authorization-service
          predicates:
            - Path=/api/v1/auth/**
            - Path=/api/v1/oauth/**

eureka:
  instance:
    hostname: localhost
