server:
  port: 8443

spring:
  application:
    name: gateway
  main:
    allow-bean-definition-overriding: true
    web-application-type: reactive
  security:
    oauth2:
      client:
        provider:
          keycloak:
            issuer-uri: http://0.0.0.0:8181/realms/master
            jwk-set-uri: http://0.0.0.0:8181/realms/master/protocol/openid-connect/certs
        registration:
          keycloak:
            client-id: needs-service
            authorization-grant-type: authorization_code
            scope: openid
    gateway:
      routes:
        - id: donations-service
          uri: ${DONATIONS_SERVICE_URL:http://localhost:8084}
          predicates:
            - Path=/api/v1/donations/**
        - id: needs-service
          uri: ${NEEDS_SERVICE_URL:http://localhost:8082}
          predicates:
            - Path=/api/v1/needs/**
        - id: shared-service
          uri: ${SHARED_SERVICE_URL:http://localhost:8085}
          predicates:
            - Path=/api/v1/cities/**, /api/v1/states/**, /api/v1/clothing/**
        - id: authorization-service
          uri: ${AUTHORIZATION_SERVICE_URL:http://localhost:8083}
          predicates:
            - Path=/api/v1/auth/**, /api/v1/oauth/**, /api/v1/otp/**

eureka:
  client:
    enabled: false

management:
  endpoints:
    web:
      exposure:
        include: "*"
  endpoint:
    health:
      show-details: always
      show-components: always
  metrics:
    tags:
      application: ${spring.application.name}
    distribution:
      percentiles-histogram:
        all: true
        http.server.requests: true
  tracing:
    sampling:
      probability: 1.0
  prometheus:
    metrics:
      export:
        step: 10s
  info:
    env:
      enabled: true
    java:
      enabled: true
    os:
      enabled: true
